### PR TITLE
removed be/le from js client, fixed testing setup

### LINKED ISSUE #146: Update `js/client` to match new JSON format
The client still uses BE/LE. Needs to be updated to have only LE

### PR DESCRIPTION
**Pull request by ErinHales**
Closes #146 

 - No tests written for this yet, going to make issue.

### CODE REVIEW

File: js/clients/lib/BcoinClient.js [hunk 1]
```diff
@@ -93,7 +93,6 @@ class BcoinClient extends NodeClient {
       vout: txinfo.vout,
       locktime: txinfo.locktime,
       tx_id: txid,
-      tx_id_le: reverse(txid),
```
Comment (prestwich) [inline js/clients/lib/BcoinClient.js:96]: these now return the BE format, right? we want that changed to LE

Comment (ErinHales) [reply js/clients/lib/BcoinClient.js:96]: Oh, yes, you're right

**Comment by prestwich** [comment]
okay. I have locally verified the client is working and produces good proofs
